### ISSUE TITLE
Question about nested modules

### ISSUE THREAD

**Issue by Pitometsu** [profburke/swiftreplmadness#1]
Hi there!
First of all, thank you a lot for your guide, @profburke!

But currently I try to load the whole package with few dependencies from swift package manager.

And got linking issue like
```
ld: library not found for -l<one_of_dependencies> for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

Also found according to this question this gist https://gist.github.com/briancroom/5d0f1b966fa9ef0ae4950e97f9d76f77

Would be glad to any suggestions.

**Comment by Pitometsu** [comment]
Ok, looks like I can achieve it by adding
```swift
products.append(
  Product(
    name: "AppName",
    type: .Library(.Dynamic),
    modules: ["AppName"]
  )
)
```
to `Package.swift`... But how just load app without modification?

**Comment by Pitometsu** [comment]
**UPD:**
build simple
```
swift build
```
and repl run by
```
swift -I .build/debug -L .build/debug -lAppName
```

**Comment by Pitometsu** [comment]
**UPD-2:** problem was with [Perfect](https://github.com/PerfectlySoft/Perfect). Thanks to their support, seems like, problem with linking to plain C library. Looks like, in Swift4 Package Manager according to [proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0146-package-manager-product-definitions.md) such behaviour may be improved, and it let fix such things in Perfect as well.
Also thereat pointed me to [pretty interesting way to use C library dynamic binding](https://github.com/RockfordWei/CSwift).

**Comment by profburke** [comment]
@Pitometsu I'm just now seeing this issue, sorry I wasn't able to help. But thanks for all the info---I've updated the repo.
